# -*- coding: utf-8 -*-
"""DinDin_Finbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xM5fzK6Bx8fMHUV88La9a-3x9PJq3LeE
"""
# main.py
import os
import gspread
from datetime import datetime
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# Cole o seu Token aqui, mas o ideal é usar variáveis de ambiente
TOKEN = "7825409619:AAEpT8G66vUhuBz42unsm5kmKSRh4bQ8sbg"

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Envia uma mensagem de boas-vindas quando o comando /start é emitido."""
    await update.message.reply_text('Olá! Eu sou seu bot financeiro. Envie /ajuda para ver os comandos.')

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Repete a mensagem do usuário."""
    await update.message.reply_text(f"Você disse: {update.message.text}")
	
async def teste_planilha(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    try:
        # Informa ao usuário que está tentando
        await update.message.reply_text("Testando conexão com a planilha, um momento...")

        # Autentica usando o arquivo credentials.json
        gc = gspread.service_account(filename='credentials.json')

        # Abre a sua planilha pelo NOME EXATO que ela tem no Google Drive
        # SUBSTITUA "Nome da Sua Planilha" PELO NOME REAL
        planilha = gc.open("Nome da Sua Planilha").sheet1

        # Adiciona uma linha de teste
        linha_teste = ["Teste do Bot", "Conexão OK!", str(datetime.now())]
        planilha.append_row(linha_teste)

        # Envia mensagem de sucesso
        await update.message.reply_text("✅ Sucesso! Uma nova linha foi adicionada à sua planilha.")

    except Exception as e:
        # Em caso de erro, informa o usuário e imprime o erro nos logs do Render
        print(f"Erro ao conectar com a planilha: {e}")
        await update.message.reply_text(f"❌ Falha ao conectar com a planilha. Verifique os logs. Erro: {e}")

def main() -> None:
    """Inicia o bot."""
    application = Application.builder().token(TOKEN).build()
	
	# Adicione o novo handler para o comando de teste
    application.add_handler(CommandHandler("DinDinFinBOT", teste_planilha))

    # Comandos
    application.add_handler(CommandHandler("start", start))

    # Responde a qualquer mensagem que não seja um comando
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))

    # Inicia o bot
    print("Bot iniciado...")
    application.run_polling()

if __name__ == "__main__":
    main()