# -*- coding: utf-8 -*-
"""DinDin_Finbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xM5fzK6Bx8fMHUV88La9a-3x9PJq3LeE
"""
# main.py
import os
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# Cole o seu Token aqui, mas o ideal é usar variáveis de ambiente
TOKEN = "7825409619:AAEpT8G66vUhuBz42unsm5kmKSRh4bQ8sbg"

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Envia uma mensagem de boas-vindas quando o comando /start é emitido."""
    await update.message.reply_text('Olá! Eu sou seu bot financeiro. Envie /ajuda para ver os comandos.')

async def echo(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Repete a mensagem do usuário."""
    await update.message.reply_text(f"Você disse: {update.message.text}")

def main() -> None:
    """Inicia o bot."""
    application = Application.builder().token(TOKEN).build()

    # Comandos
    application.add_handler(CommandHandler("start", start))

    # Responde a qualquer mensagem que não seja um comando
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, echo))

    # Inicia o bot
    print("Bot iniciado...")
    application.run_polling()

if __name__ == "__main__":
    main()